### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by Anay028** [dozoisch/react-google-recaptcha#269]
react-google-recaptcha version: ^2.1.0
react-script version: 5.0.1

Here's the full error:

Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/FFtxPnbuZxq6kkeHkQJR2MNQ/recaptcha__en.js:475:34)
    at eS.<anonymous> (https://www.gstatic.com/recaptcha/releases/FFtxPnbuZxq6kkeHkQJR2MNQ/recaptcha__en.js:311:36)

It has started happening since I tried to add transition to my code

**Comment by Anay028** [comment]
This issue is caused when the recaptcha element is not in the document
