### ISSUE TITLE
 'ReCAPTCHA' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by shyam-stha** [dozoisch/react-google-recaptcha#277]
react-google-recaptcha version: 2.1.0
react-async-script version: Y.Y.Y

Type error: 'ReCAPTCHA' cannot be used as a JSX component.
  Its instance type 'ReCAPTCHA' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/app/node_modules/@types/react-dom/node_modules/@types/react/ts5.0/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.

**Comment by megacherry** [comment]
It's related to @types/react. Downgrade to 18.2.12 will help.

**Comment by spietrek-insight** [comment]
Same error

**Comment by henriques4nti4go** [comment]
same error

**Comment by rdok** [comment]
Caused by latest version of `@types/react`: `18.2.28`. 

In my case reverting to last known working state `18.2.23` resolves (at least temporarily) the issue.

**Comment by davidgamez** [comment]
I found the same issue and applied the following workaround that fixed it: https://stackoverflow.com/a/75093164

**Comment by MadaShindeInai** [comment]
Same error! @types/react": "18.2.37

**Comment by 127** [comment]
Same problem here in Remix 2.3.1 and TSX:
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-google-recaptcha": "^3.1.0",
recaptcha requires types to be imported 
"@types/react-google-recaptcha": "^2.1.8",
`import { ReCAPTCHA } from "react-google-recaptcha";`
if imported like that fails: 
`import ReCAPTCHA from "react-google-recaptcha";`
```

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6109:9)
    at renderNodeDestructiveImpl (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderNode (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6325:12)
    at renderChildrenArray (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6277:7)
    at renderNodeDestructiveImpl (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6207:7)
    at renderNodeDestructive (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderNode (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6325:12)
    at renderHostElement (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/Users/localuser/testproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:6018:5)
```
Looks like it doesn't even injects google recaptcha script element to DOM. 
Inited like <ReCAPTCHA sitekey={ loaderData.rkey! } theme="dark" />

**Comment by 127** [comment]
> I found the same issue and applied the following workaround that fixed it: https://stackoverflow.com/a/75093164

Note: this one doesn't work for  Remix 2.3.1

**Comment by eeshankeni** [comment]
Same here, tried installing @types/react-google-recaptcha but that didnt help

**Comment by 127** [comment]
> Same here, tried installing @types/react-google-recaptcha but that didnt help

Switched to `react-google-recaptcha-ultimate`. This package works.

**Comment by eeshankeni** [comment]
adding this to my tsconfig compiler options seems to have fixed the issue for now.

"paths": {
      "react": [ "./node_modules/@types/react" ]
    }

**Comment by Yaroslavpnts** [comment]
@127 
`react-google-recaptcha-ultimate` this package deprecated, Did you find solution for `react-google-recaptcha`?

**Comment by Yaroslavpnts** [comment]
@eeshankeni 
For me your variant didn't work, maybe you did some additional configurations?

**Comment by 127** [comment]
> @127 `react-google-recaptcha-ultimate` this package deprecated, Did you find solution for `react-google-recaptcha`?

yes, as recommended switched to "@google-recaptcha/react": "^1.0.1",

**Comment by jnasoy** [comment]
Does anyone figured out a solution without downgrading the react types? Adding the paths in config does not help as well

**Comment by fuchinoko** [comment]
is this package abandoned?

**Comment by 127** [comment]
Looks like

**Comment by mrcMesen** [comment]
I fixed my issue by removing the `yarn.lock` file and `node_modules` folder and reinstall

**Comment by djpremier** [comment]
Hi, I managed to "solve" it by writing the typing locally.

### react-google-recaptcha.d.ts

```ts
declare module "react-google-recaptcha" {
  import * as React from "react";

  interface ReCAPTCHAProps {
    sitekey: string;
    onChange?: (token: string | null) => void;
    grecaptcha?: object;
    theme?: "light" | "dark";
    type?: "image" | "audio";
    tabindex?: number;
    onExpired?: () => void;
    asyncScriptOnLoad?: () => void;
    onErrored?: () => void;
    stoken?: string;
    hl?: string;
    size?: "compact" | "normal" | "invisible";
    badge?: "bottomright" | "bottomleft" | "inline";
    isolated?: boolean;
  }

  class ReCAPTCHA extends React.Component<ReCAPTCHAProps> {
    reset(): void;
    execute(): void;
    executeAsync(): Promise<string | null>;
    getValue(): string | null;
    getWidgetId(): number | null;
  }

  export default ReCAPTCHA;
}
```

**Comment by resatyildiz** [comment]
> adding this to my tsconfig compiler options seems to have fixed the issue for now.
> 
> "paths": { "react": [ "./node_modules/@types/react" ] }

I'm using with next.js v15, it works for me.

**Comment by bibashpoudel7** [comment]
# add to the tsconfig.json 
## this will fix the issue

```
{
  "compilerOptions": {
    ...
    "paths": {
      "react": [ "./node_modules/@types/react" ]
    }
  }
}
```

**Comment by hoanmq** [comment]
> Hi, I managed to "solve" it by writing the typing locally.
> 
> ### react-google-recaptcha.d.ts
> ```ts
> declare module "react-google-recaptcha" {
>   import * as React from "react";
> 
>   interface ReCAPTCHAProps {
>     sitekey: string;
>     onChange?: (token: string | null) => void;
>     grecaptcha?: object;
>     theme?: "light" | "dark";
>     type?: "image" | "audio";
>     tabindex?: number;
>     onExpired?: () => void;
>     asyncScriptOnLoad?: () => void;
>     onErrored?: () => void;
>     stoken?: string;
>     hl?: string;
>     size?: "compact" | "normal" | "invisible";
>     badge?: "bottomright" | "bottomleft" | "inline";
>     isolated?: boolean;
>   }
> 
>   class ReCAPTCHA extends React.Component<ReCAPTCHAProps> {
>     reset(): void;
>     execute(): void;
>     executeAsync(): Promise<string | null>;
>     getValue(): string | null;
>     getWidgetId(): number | null;
>   }
> 
>   export default ReCAPTCHA;
> }
> ```

Thanks! It's work perfect for me

**Comment by felixcaronpare** [comment]
Hi, I ran into this problem while using reCAPTCHA in a React component within as Astro project.

Adding `client:only="react"` to the component  with the captcha fixes the issue for Astro/React project.

The reason is Astro uses server-side rendering but that doesn't mix well with the react-google-captcha library, so you have to use `client:only` to tell Astro to load it on the browser instead of the server.

**Comment by yunsii** [comment]
I solved it with pnpm overrides: https://pnpm.io/settings#overrides

```
overrides:
  '@types/react-google-recaptcha@^2>@types/react': 18.0.18
```

It will install @types/react@19.1.8 when I install @types/react-google-recaptcha directly for now, after I review the pnpm-lock.yaml. So I tried the overrides feature to limit the @types/react version, and then it works 😄
